version: 0.2
env:
  variables:
    S3_ENVIRONMENT_BUCKET: "enumv2-environmentvariable"
    Project: "frontend"
    Service: "systest"
    ENVIRONMENT_FILE: "enumv2-systest-frontend"
 #phases:
     #commands:
     # - npm i npm@latest -g
     # - pip install --upgrade pip
     # - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
      #- npm install -g npm@latest
      - npm ci
  build:
    commands:
      - aws s3 cp s3://${S3_ENVIRONMENT_BUCKET}/${Project}/${Service}/${ENVIRONMENT_FILE} .env
      - echo Build Phase
      - npm run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./dist s3://systestv2-enum.africa
      - aws cloudfront create-invalidation --distribution-id E1WXOPIX3Q52HG --paths "/*";